//! Thin-filament Biot–Savart evaluation of the racetrack centerline.
//!
//! The cell evaluator (`racetrack.rs`) models the finite winding-pack
//! cross-section; this module models the *other* limit — the pack's
//! centerline carrying `ampere_turns_a` as a single filament — which is
//! what independent implementations (OC-011's Bluemira
//! `BiotSavartFilament`) answer directly. Keeping both models in-tree
//! means the cross-check compares the same declared model on both sides.
//!
//! Each straight/arc chord segment contributes the exact finite-wire
//! Biot–Savart term
//!   B = mu0 I / (4 pi d^2) * (u x n) * (v1.u/|v1| - v2.u/|v2|)
//! with `n` the perpendicular vector from the segment line to the probe.
//! Only the arc discretization is approximate (~1/K^2 in the segment
//! count K); straights are exact at any K.

use optcoil_model::magnetics::Racetrack;
use optcoil_model::path::{CoilPath, PathSegment};

const MU0_OVER_4PI: f64 = 1e-7; // mu0 / (4 pi) exactly, in SI
/// Arc segments per semicircle bend. Relative discretization error is
/// ~(pi/K)^2 ~ 6e-5 at K=512 — far below the cross-check's 1e-3 gate.
const ARC_SEGMENTS: usize = 512;
/// Chord count per straight; the straight-segment formula is exact, so
/// a single chord per straight would suffice — a few subdivisions keep
/// the loop's segment structure symmetric.
const STRAIGHT_CHORDS: usize = 4;

/// Field of the racetrack centerline filament at `probe_m`, tesla.
/// Returns `None` when the probe lies on the conductor (singular) or
/// the geometry is degenerate (R <= 0 or nonfinite inputs).
pub fn racetrack_filament_field(geometry: &Racetrack, probe_m: [f64; 3]) -> Option<[f64; 3]> {
    let l = geometry.straight_half_length_m;
    let r = geometry.bend_radius_m;
    if !r.is_finite() || r <= 0.0 || !l.is_finite() || l < 0.0 {
        return None;
    }
    let mut b = [0.0_f64; 3];
    for (a, c) in segments(l, r) {
        b = add(b, segment_field(geometry.ampere_turns_a, a, c, probe_m)?);
    }
    Some(b)
}

/// Centerline as a closed polygon, wound in the cell evaluator's
/// convention (Part::Top tangent is -x at +y, Part::Bottom +x at -y;
/// arcs sweep counterclockwise seen from +z): bottom straight -l->+l,
/// right semicircle bulging +x, top straight +l->-l, left semicircle
/// bulging -x. That circulation gives +B_z inside the loop for
/// positive ampere-turns, matching the cell evaluator.
fn segments(l: f64, r: f64) -> Vec<([f64; 3], [f64; 3])> {
    let mut path = Vec::new();
    // Bottom straight: (-l, -r) -> (+l, -r)
    push_line(&mut path, [-l, -r, 0.0], [l, -r, 0.0], STRAIGHT_CHORDS);
    // Right arc: (l, -r) -> (l, +r), centre (l, 0), angle -pi/2 -> +pi/2
    // through 0 (the arc's outermost point is (l+r, 0)).
    push_arc(
        &mut path,
        [l, 0.0],
        r,
        -std::f64::consts::FRAC_PI_2,
        std::f64::consts::FRAC_PI_2,
    );
    // Top straight: (+l, +r) -> (-l, +r)
    push_line(&mut path, [l, r, 0.0], [-l, r, 0.0], STRAIGHT_CHORDS);
    // Left arc: (-l, +r) -> (-l, -r), centre (-l, 0), angle +pi/2 ->
    // +3pi/2 through pi (outermost (-l-r, 0)).
    push_arc(
        &mut path,
        [-l, 0.0],
        r,
        std::f64::consts::FRAC_PI_2,
        3.0 * std::f64::consts::FRAC_PI_2,
    );
    path
}

/// Field of a general `CoilPath` centerline filament at `probe_m`, tesla,
/// carrying `ampere_turns_a` as a single filament current. Chords are
/// generated by walking the path with `pose_at`: lines split into a few
/// exact chords, arcs into `ARC_SEGMENTS` chords each (~K^-2
/// discretization error, same as `racetrack_filament_field`). Returns
/// `None` when the probe lies on the conductor or the path is invalid.
pub fn path_filament_field(
    path: &CoilPath,
    ampere_turns_a: f64,
    probe_m: [f64; 3],
) -> Option<[f64; 3]> {
    if !ampere_turns_a.is_finite() || probe_m.iter().any(|x| !x.is_finite()) {
        return None;
    }
    path.validate().ok()?;
    let mut b = [0.0_f64; 3];
    let mut s = 0.0;
    for segment in &path.segments {
        let chords = match segment {
            PathSegment::Line { .. } => STRAIGHT_CHORDS,
            PathSegment::Arc { .. } => ARC_SEGMENTS,
        };
        let seg_len = segment.length_m();
        let mut prev = path.pose_at(s).ok()?.position_m;
        for i in 1..=chords {
            let next = path
                .pose_at(s + seg_len * i as f64 / chords as f64)
                .ok()?
                .position_m;
            b = add(b, segment_field(ampere_turns_a, prev, next, probe_m)?);
            prev = next;
        }
        s += seg_len;
    }
    Some(b)
}

fn push_line(path: &mut Vec<([f64; 3], [f64; 3])>, a: [f64; 3], b: [f64; 3], chords: usize) {
    for i in 0..chords {
        let t0 = i as f64 / chords as f64;
        let t1 = (i + 1) as f64 / chords as f64;
        let lerp = |a: f64, b: f64, t: f64| a + (b - a) * t;
        path.push((
            [lerp(a[0], b[0], t0), lerp(a[1], b[1], t0), 0.0],
            [lerp(a[0], b[0], t1), lerp(a[1], b[1], t1), 0.0],
        ));
    }
}

fn push_arc(path: &mut Vec<([f64; 3], [f64; 3])>, center: [f64; 2], radius: f64, a0: f64, a1: f64) {
    let point = |a: f64| {
        [
            center[0] + radius * a.cos(),
            center[1] + radius * a.sin(),
            0.0,
        ]
    };
    let mut prev = point(a0);
    for i in 1..=ARC_SEGMENTS {
        let a = a0 + (a1 - a0) * i as f64 / ARC_SEGMENTS as f64;
        let next = point(a);
        path.push((prev, next));
        prev = next;
    }
}

/// Exact Biot–Savart contribution of one finite straight segment a->b at
/// probe `p`, for filament current `current_a`. None when the probe sits
/// on the segment (perpendicular distance ~0).
fn segment_field(current_a: f64, a: [f64; 3], b: [f64; 3], p: [f64; 3]) -> Option<[f64; 3]> {
    let ab = [b[0] - a[0], b[1] - a[1], b[2] - a[2]];
    let len = (ab[0] * ab[0] + ab[1] * ab[1] + ab[2] * ab[2]).sqrt();
    if len <= 0.0 {
        return Some([0.0; 3]);
    }
    let u = [ab[0] / len, ab[1] / len, ab[2] / len];
    let v1 = [p[0] - a[0], p[1] - a[1], p[2] - a[2]];
    let v2 = [p[0] - b[0], p[1] - b[1], p[2] - b[2]];
    let v1_dot_u = v1[0] * u[0] + v1[1] * u[1] + v1[2] * u[2];
    let n = [
        v1[0] - v1_dot_u * u[0],
        v1[1] - v1_dot_u * u[1],
        v1[2] - v1_dot_u * u[2],
    ];
    let d2 = n[0] * n[0] + n[1] * n[1] + n[2] * n[2];
    if d2 < 1e-24 {
        return None; // probe on the conductor — singular
    }
    let m1 = (v1[0] * v1[0] + v1[1] * v1[1] + v1[2] * v1[2]).sqrt();
    let m2 = (v2[0] * v2[0] + v2[1] * v2[1] + v2[2] * v2[2]).sqrt();
    // (v1.u/|v1| - v2.u/|v2|): +2 for an infinite wire, so the field
    // reduces to mu0 I / (2 pi d).
    let bracket = v1_dot_u / m1 - (v2[0] * u[0] + v2[1] * u[1] + v2[2] * u[2]) / m2;
    let ux_n = [
        u[1] * n[2] - u[2] * n[1],
        u[2] * n[0] - u[0] * n[2],
        u[0] * n[1] - u[1] * n[0],
    ];
    let scale = MU0_OVER_4PI * current_a * bracket / d2;
    Some([scale * ux_n[0], scale * ux_n[1], scale * ux_n[2]])
}

fn add(a: [f64; 3], b: [f64; 3]) -> [f64; 3] {
    [a[0] + b[0], a[1] + b[1], a[2] + b[2]]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::circular_loop_axis_bz_t;
    use optcoil_model::magnetics::CurrentModel;

    fn loop_geometry(radius: f64, ampere_turns: f64) -> Racetrack {
        Racetrack {
            straight_half_length_m: 0.0,
            bend_radius_m: radius,
            radial_width_m: 0.01,
            axial_height_m: 0.01,
            ampere_turns_a: ampere_turns,
            current_model: CurrentModel::UniformWindingPack,
        }
    }

    #[test]
    fn circular_loop_matches_the_closed_form_on_axis() {
        // L=0: two semicircles back-to-back make a full loop of radius R
        // in the z=0 plane — the in-tree closed form is the reference.
        for z in [0.0, 0.01, -0.05, 0.1] {
            let b =
                racetrack_filament_field(&loop_geometry(0.03, 100_000.0), [0.0, 0.0, z]).unwrap();
            let expected = circular_loop_axis_bz_t(0.03, z, 100_000.0).unwrap();
            assert!(
                (b[2] - expected).abs() < 1e-3 * expected.max(1e-9),
                "z={z}: filament {:.8e} vs closed form {:.8e}",
                b[2],
                expected
            );
            assert!(b[0].abs() < 1e-9 && b[1].abs() < 1e-9);
        }
    }

    #[test]
    fn path_filament_agrees_with_the_racetrack_walker() {
        // The general `CoilPath` discretization must reproduce the
        // racetrack-specific loop on identical geometry.
        let mut g = loop_geometry(0.05, 50_000.0);
        g.straight_half_length_m = 0.4;
        let path = CoilPath::racetrack(g.straight_half_length_m, g.bend_radius_m);
        for probe in [[0.1, 0.02, 0.0], [0.0, 0.0, 0.3], [-0.2, 0.06, -0.1]] {
            let a = racetrack_filament_field(&g, probe).unwrap();
            let b = path_filament_field(&path, g.ampere_turns_a, probe).unwrap();
            let diff = [a[0] - b[0], a[1] - b[1], a[2] - b[2]];
            let mag = (a[0] * a[0] + a[1] * a[1] + a[2] * a[2]).sqrt();
            assert!(
                diff.iter().map(|x| x * x).sum::<f64>().sqrt() < 1e-9 * mag.max(1e-9),
                "probe {probe:?}: {a:?} vs {b:?}"
            );
        }
    }

    #[test]
    fn straight_dominated_region_matches_an_infinite_pair() {
        // Near the middle of long straights the arcs are far away; the
        // field approaches two opposing infinite wires:
        // B_z ~ mu0 I / (2 pi) * (1/(R-y) + 1/(R+y)) for |y| < R.
        let mut g = loop_geometry(0.05, 50_000.0);
        g.straight_half_length_m = 5.0; // arcs 5 m away — negligible
        let b = racetrack_filament_field(&g, [0.0, 0.02, 0.0]).unwrap();
        let infinite = 2e-7 * 50_000.0 * (1.0 / (0.05 - 0.02) + 1.0 / (0.05 + 0.02));
        assert!(
            (b[2] - infinite).abs() < 1e-3 * infinite,
            "filament {:.8e} vs infinite-pair {:.8e}",
            b[2],
            infinite
        );
    }
}
